name: cabal

on:
  push:
    branches: [ci-cabal]
  pull_request:
    branches: [master]

jobs:
  build:
    name: ghc ${{ matrix.ghc }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        cabal: ["3.4"]
        ghc:
          - "8.4.4"

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - uses: haskell/actions/setup@v1
      name: Setup GHC and cabal-install
      with:
        ghc-version: ${{ matrix.ghc }}
        cabal-version: ${{ matrix.cabal }}

    - uses: actions/cache@v2
      name: cache ~/.cabal/store
      with:
        path: ~/.cabal/store
        key: ${{ runner.os }}-${{ matrix.ghc }}-cabal

    - uses: pavpanchekha/setup-z3@1.2.2
      name: setup z3
      with:
        version: "4.8.7"

    - name: build
      run: |
        cabal v2-update
        cabal v2-build all:libs
        cabal v2-build thoralf-plugin:rows --enable-tests
        cabal v2-build thoralf-plugin:units --enable-tests

    - name: test thoralf rows
      run: cabal v2-test thoralf-plugin:rows --test-show-details=direct --test-option="--color=always"

    - name: test thoralf units
      run: cabal v2-test thoralf-plugin:units --test-show-details=direct --test-option="--color=always"